"""Common shared utilities for the au Jibun Bank AI Agent."""

from src.common.errors import (
    AppError,
    BedrockError,
    BedrockThrottledError,
    ComprehendError,
    ConfigError,
    ContactLensError,
    CrawlerError,
    CrmApiError,
    DynamoAccessError,
    EmbeddingError,
    FetchTimeoutError,
    NotFoundError,
    ObjectNotFoundError,
    ParseError,
    ProfileLookupError,
    ResponseParseError,
    RobotsDisallowedError,
    RobotsNotLoadedError,
    S3AccessError,
    SearchError,
    SecretsError,
    SessionNotFoundError,
    TimeoutBudgetExceeded,
    UnauthorizedError,
    ValidationError,
)

__all__ = [
    "AppError",
    "BedrockError",
    "BedrockThrottledError",
    "ComprehendError",
    "ConfigError",
    "ContactLensError",
    "CrawlerError",
    "CrmApiError",
    "DynamoAccessError",
    "EmbeddingError",
    "FetchTimeoutError",
    "NotFoundError",
    "ObjectNotFoundError",
    "ParseError",
    "ProfileLookupError",
    "ResponseParseError",
    "RobotsDisallowedError",
    "RobotsNotLoadedError",
    "S3AccessError",
    "SearchError",
    "SecretsError",
    "SessionNotFoundError",
    "TimeoutBudgetExceeded",
    "UnauthorizedError",
    "ValidationError",
]
